site_name: My site
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/dna
  favicon: assets/images/dna-svgrepo-com.svg

# Repository
repo_name: sib-swiss/NGS-variant-training
repo_url: https://github.com/sib-swiss/NGS-variant-training
edit_uri: ""

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
